### ISSUE TITLE
Webpack loader issues -morning-session-group-collins-tendai-luqman-abi-1718

### ISSUE THREAD

**Issue by tnyandoro** [tnyandoro/the-todo-list#2]
When I run this script, the HTML document is not loaded. 
Webpack loaders have been fixed

**Comment by Metsanpeitto** [comment]
## Status: Approved :green_circle: 

### Congratulations @tnyandoro  :tada: :clinking_glasses: 

_Good Job fixing the Webpack loaders_

**Your project is complete!  This is a convenient point to merge :rocket:**

**Comment(s)**
- You might want to update the `Getting Started` section of your Readme. This should only contain the instructions to set up the project, not the project requirements. You might want to add steps involved in installing the project dependencies (`npm install`) and running the project on the dev environment (`npm start`).
- - - - - -

**_Feel free to leave any questions or comments in the PR thread if something is not 100% clear._**

Do not forget to fill the project completion form, as this is important for your weekly progress score.

**_Good luck with your next task._**

* * * 
_Cheers,_
**[Abraham R](https://github.com/Metsanpeitto/)**
__Happy Coding :smiley:__
